# Generated by Django 6.1.1 on 2026-09-30 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_name', models.CharField(default='NothigHub', max_length=100)),
                ('support_email', models.EmailField(default='sadat2151@gmail.com', max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
