# Generated by Django 6.1.1 on 2026-10-03 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=200, unique=True)),
                ('product_slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('product_description', models.TextField(blank=True)),
                ('product_price', models.FloatField()),
                ('product_discount_price', models.FloatField()),
                ('product_stock', models.IntegerField()),
                ('product_is_available', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
        ),
    ]
